version: '4.9'
services:
    web:
        build: ./movieView
        ports:
            - 3000:3000
    api:
        build: ./movieDB
        ports:
            - 3001:3001
        environment:
            DB_URL: mongodb://db/moviedb
    db:
        image: mongo:6.0
        ports:
            - 27017:27017
        volumes:
            - moviedb:/data/db
volumes:
    moviedb
       
version: '3'
services:
  frontend:
    build:
      context: ./movieView
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./movieDB
    ports:
      - "8080:8080"
    # depends_on:
    #   - mongo
    
#   db:
#     image: mongo
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db
